/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/lioneljouin/devicenetwork/apis/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DeviceNetworkLister helps list DeviceNetworks.
// All objects returned here must be treated as read-only.
type DeviceNetworkLister interface {
	// List lists all DeviceNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.DeviceNetwork, err error)
	// Get retrieves the DeviceNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.DeviceNetwork, error)
	DeviceNetworkListerExpansion
}

// deviceNetworkLister implements the DeviceNetworkLister interface.
type deviceNetworkLister struct {
	listers.ResourceIndexer[*apisv1alpha1.DeviceNetwork]
}

// NewDeviceNetworkLister returns a new DeviceNetworkLister.
func NewDeviceNetworkLister(indexer cache.Indexer) DeviceNetworkLister {
	return &deviceNetworkLister{listers.New[*apisv1alpha1.DeviceNetwork](indexer, apisv1alpha1.Resource("devicenetwork"))}
}
