/*
Copyright (c) 2026

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apisv1alpha1 "github.com/lioneljouin/devicenetwork/apis/v1alpha1"
	scheme "github.com/lioneljouin/devicenetwork/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DeviceNetworksGetter has a method to return a DeviceNetworkInterface.
// A group's client should implement this interface.
type DeviceNetworksGetter interface {
	DeviceNetworks() DeviceNetworkInterface
}

// DeviceNetworkInterface has methods to work with DeviceNetwork resources.
type DeviceNetworkInterface interface {
	Create(ctx context.Context, deviceNetwork *apisv1alpha1.DeviceNetwork, opts v1.CreateOptions) (*apisv1alpha1.DeviceNetwork, error)
	Update(ctx context.Context, deviceNetwork *apisv1alpha1.DeviceNetwork, opts v1.UpdateOptions) (*apisv1alpha1.DeviceNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, deviceNetwork *apisv1alpha1.DeviceNetwork, opts v1.UpdateOptions) (*apisv1alpha1.DeviceNetwork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.DeviceNetwork, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.DeviceNetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.DeviceNetwork, err error)
	DeviceNetworkExpansion
}

// deviceNetworks implements DeviceNetworkInterface
type deviceNetworks struct {
	*gentype.ClientWithList[*apisv1alpha1.DeviceNetwork, *apisv1alpha1.DeviceNetworkList]
}

// newDeviceNetworks returns a DeviceNetworks
func newDeviceNetworks(c *DevicenetworkV1alpha1Client) *deviceNetworks {
	return &deviceNetworks{
		gentype.NewClientWithList[*apisv1alpha1.DeviceNetwork, *apisv1alpha1.DeviceNetworkList](
			"devicenetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apisv1alpha1.DeviceNetwork { return &apisv1alpha1.DeviceNetwork{} },
			func() *apisv1alpha1.DeviceNetworkList { return &apisv1alpha1.DeviceNetworkList{} },
		),
	}
}
