---
apiVersion: devicenetwork.io/v1alpha1
kind: DeviceNetwork
metadata:
  name: my-network
spec:
  deviceSelectors:
  - name: "dummy-interfaces"
    nodeSelector:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
    selectors:
    - cel:
        expression: interfaceName.startsWith("dummy")
  deviceConfigurations: 
  - name: "macvlan"
    deviceType: Macvlan
    deviceSelectors:
    - "dummy-interfaces"
  networkInterfaceConfiguration:
    ipam:
    - provider: Random
      random:
        cidr: "192.168.1.0/24"