#!/usr/bin/env bash
# This file was generated by AI.
#
# Copyright 2026
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Manage a QEMU-based e2e test cluster with SR-IOV (igb) emulation.
#
# Prerequisites: qemu-system-x86_64, qemu-img, genisoimage (or mkisofs/xorriso),
#                curl, ssh, KVM support (/dev/kvm).
#
# Usage:
#   hack/e2e/e2e-cluster.sh build       Build base VM image (~60s, one-time)
#   hack/e2e/e2e-cluster.sh up          Start cluster (~5s with direct kernel boot)
#   hack/e2e/e2e-cluster.sh down        Stop cluster
#   hack/e2e/e2e-cluster.sh ssh [cmd]   SSH into the VM
#   hack/e2e/e2e-cluster.sh kubeconfig  Print kubeconfig path
#   hack/e2e/e2e-cluster.sh deploy      Build and deploy DeviceNetwork into the cluster

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

E2E_DIR="${E2E_DIR:-${PROJECT_DIR}/_output/e2e}"
ALPINE_VERSION="${ALPINE_VERSION:-3.21}"
ALPINE_RELEASE="${ALPINE_RELEASE:-3.21.6}"
K3S_VERSION="${K3S_VERSION:-v1.33.1+k3s1}"
VM_MEMORY="${VM_MEMORY:-4096}"
VM_CPUS="${VM_CPUS:-4}"
SSH_PORT="${SSH_PORT:-2222}"
API_PORT="${API_PORT:-6443}"
IGB_COUNT="${IGB_COUNT:-2}"
SRIOV_VF_COUNT="${SRIOV_VF_COUNT:-4}"

BASE_IMAGE="${E2E_DIR}/base.qcow2"
OVERLAY_IMAGE="${E2E_DIR}/overlay.qcow2"
SEED_ISO="${E2E_DIR}/seed.iso"
SSH_KEY="${E2E_DIR}/id_ed25519"
QEMU_PID="${E2E_DIR}/qemu.pid"
KUBECONFIG_PATH="${E2E_DIR}/kubeconfig"
SERIAL_LOG="${E2E_DIR}/serial.log"
KERNEL="${E2E_DIR}/vmlinuz-lts"
INITRD="${E2E_DIR}/initramfs-lts"
CLOUD_IMAGE="${E2E_DIR}/alpine-cloud.qcow2"
ROOT_DEV_FILE="${E2E_DIR}/root-device"

CLOUD_IMAGE_URL="https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/releases/cloud/nocloud_alpine-${ALPINE_RELEASE}-x86_64-bios-cloudinit-r0.qcow2"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

ssh_cmd() {
    ssh -q \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o ConnectTimeout=5 \
        -i "$SSH_KEY" \
        -p "$SSH_PORT" \
        root@localhost "$@"
}

scp_from() {
    scp -q \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -i "$SSH_KEY" \
        -P "$SSH_PORT" \
        "root@localhost:$1" "$2"
}

wait_ssh() {
    local timeout="${1:-120}"
    local start=$SECONDS
    echo "  Waiting for SSH..."
    while ! ssh_cmd true 2>/dev/null; do
        if (( SECONDS - start > timeout )); then
            echo "ERROR: SSH not reachable after ${timeout}s"
            return 1
        fi
        sleep 1
    done
}

wait_k3s() {
    local timeout="${1:-120}"
    echo "  Waiting for k3s..."
    local start=$SECONDS
    while ! ssh_cmd "k3s kubectl get nodes 2>/dev/null | grep -q ' Ready'" 2>/dev/null; do
        if (( SECONDS - start > timeout )); then
            echo "ERROR: k3s not ready after ${timeout}s"
            return 1
        fi
        sleep 2
    done
}

check_running() {
    [[ -f "$QEMU_PID" ]] && kill -0 "$(cat "$QEMU_PID")" 2>/dev/null
}

make_seed_iso() {
    local tmpdir
    tmpdir=$(mktemp -d)
    trap "rm -rf $tmpdir" RETURN

    local ssh_pubkey
    ssh_pubkey=$(cat "${SSH_KEY}.pub")

    cat > "$tmpdir/meta-data" <<EOF
instance-id: e2e-node
local-hostname: e2e-node
EOF

    # cloud-init user-data as a shell script
    cat > "$tmpdir/user-data" <<USERDATA
#!/bin/sh
set -ex

# SSH
mkdir -p /root/.ssh
echo "${ssh_pubkey}" > /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys

# Enable community repo for k3s dependencies
sed -i 's|^#\(.*community\)|\1|' /etc/apk/repositories
apk update

# Install the LTS kernel (has igb/igbvf drivers; linux-virt does not)
apk add linux-lts

# Install dependencies
apk add --no-cache bash curl pciutils iproute2 iptables cni-plugins

# Enable cgroups v2 (required by k3s)
rc-update add cgroups default
rc-service cgroups start || true

# Load modules on boot
cat >> /etc/modules <<MODULES
igb
igbvf
br_netfilter
MODULES

# Install k3s
curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION="${K3S_VERSION}" \
    INSTALL_K3S_EXEC="server \
        --disable=traefik \
        --disable=metrics-server \
        --disable=servicelb \
        --node-name=e2e-node \
        --write-kubeconfig-mode=644" \
    sh -

touch /var/lib/cloud-init-done
USERDATA

    if command -v genisoimage &>/dev/null; then
        genisoimage -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
            "$tmpdir/user-data" "$tmpdir/meta-data"
    elif command -v mkisofs &>/dev/null; then
        mkisofs -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
            "$tmpdir/user-data" "$tmpdir/meta-data"
    elif command -v xorriso &>/dev/null; then
        xorriso -as mkisofs -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
            "$tmpdir/user-data" "$tmpdir/meta-data"
    else
        echo "ERROR: Need genisoimage, mkisofs, or xorriso to create the seed ISO."
        return 1
    fi
}

launch_qemu() {
    local image="$1"
    shift
    local extra_args=("$@")

    local qemu_args=(
        qemu-system-x86_64
        -machine q35,accel=kvm
        -cpu host
        -m "$VM_MEMORY"
        -smp "$VM_CPUS"
        -display none
        -serial "file:${SERIAL_LOG}"
        -drive "file=${image},if=virtio,format=qcow2"
        -netdev "user,id=mgmt,hostfwd=tcp::${SSH_PORT}-:22,hostfwd=tcp::${API_PORT}-:6443"
        -device virtio-net-pci,netdev=mgmt
    )

    for i in $(seq 1 "$IGB_COUNT"); do
        qemu_args+=(
            -device "pcie-root-port,id=rp${i},slot=${i}"
            -device "igb,bus=rp${i},id=igb${i}"
        )
    done

    qemu_args+=("${extra_args[@]}")

    "${qemu_args[@]}" &
    echo $! > "$QEMU_PID"
}

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------

cmd_build() {
    echo "=== Building e2e base image ==="
    mkdir -p "$E2E_DIR"

    if [[ ! -f "$SSH_KEY" ]]; then
        ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -q
        echo "  Generated SSH key."
    fi

    if [[ ! -f "$CLOUD_IMAGE" ]]; then
        echo "  Downloading Alpine ${ALPINE_RELEASE} cloud image..."
        curl -fSL --progress-bar -o "$CLOUD_IMAGE" "$CLOUD_IMAGE_URL"
    fi

    cp "$CLOUD_IMAGE" "$BASE_IMAGE"
    qemu-img resize -q "$BASE_IMAGE" 10G

    make_seed_iso

    echo "  Provisioning VM (one-time, takes ~60-90s)..."
    launch_qemu "$BASE_IMAGE" \
        -drive "file=${SEED_ISO},if=virtio,media=cdrom"

    wait_ssh 180

    echo "  Waiting for cloud-init..."
    local start=$SECONDS
    while ! ssh_cmd "test -f /var/lib/cloud-init-done" 2>/dev/null; do
        if (( SECONDS - start > 300 )); then
            echo "ERROR: cloud-init timed out"
            cmd_down
            return 1
        fi
        sleep 5
    done

    wait_k3s 180

    echo "  Extracting LTS kernel + initrd for direct boot..."
    scp_from "/boot/vmlinuz-lts" "$KERNEL"
    scp_from "/boot/initramfs-lts" "$INITRD"

    echo "  Detecting root device..."
    ssh_cmd "findmnt -n -o SOURCE /" > "$ROOT_DEV_FILE"
    echo "  Root device: $(cat "$ROOT_DEV_FILE")"

    echo "  Shutting down..."
    ssh_cmd "poweroff" || true
    sleep 3
    if check_running; then
        kill "$(cat "$QEMU_PID")" 2>/dev/null || true
    fi
    rm -f "$QEMU_PID"

    echo "=== Base image ready ==="
    echo "  Image:   $BASE_IMAGE"
    echo "  Kernel:  $KERNEL"
    echo "  Initrd:  $INITRD"
}

cmd_up() {
    if check_running; then
        echo "Cluster already running (PID $(cat "$QEMU_PID"))."
        return 0
    fi

    for f in "$BASE_IMAGE" "$KERNEL" "$INITRD" "$ROOT_DEV_FILE"; do
        if [[ ! -f "$f" ]]; then
            echo "Missing $f — run 'build' first."
            return 1
        fi
    done

    echo "=== Starting e2e cluster ==="

    local root_dev
    root_dev=$(cat "$ROOT_DEV_FILE")

    qemu-img create -q -f qcow2 -b "$BASE_IMAGE" -F qcow2 "$OVERLAY_IMAGE"

    launch_qemu "$OVERLAY_IMAGE" \
        -kernel "$KERNEL" \
        -initrd "$INITRD" \
        -append "root=${root_dev} modules=ext4,igb,igbvf console=ttyS0 quiet"

    wait_ssh 30
    wait_k3s 60

    echo "  Creating SR-IOV VFs on igb PFs..."
    ssh_cmd "modprobe igb; modprobe igbvf" || true
    local pf_addrs
    pf_addrs=$(ssh_cmd "ls -d /sys/bus/pci/drivers/igb/0000:* 2>/dev/null | xargs -I{} basename {}" || true)
    for addr in $pf_addrs; do
        ssh_cmd "echo ${SRIOV_VF_COUNT} > /sys/bus/pci/devices/${addr}/sriov_numvfs" 2>/dev/null || true
        local pf_iface
        pf_iface=$(ssh_cmd "ls /sys/bus/pci/devices/${addr}/net/ 2>/dev/null | head -1" || true)
        echo "  PF ${addr} (${pf_iface:-unknown}): ${SRIOV_VF_COUNT} VFs"
    done

    scp_from "/etc/rancher/k3s/k3s.yaml" "$KUBECONFIG_PATH"
    sed -i "s|127.0.0.1:6443|127.0.0.1:${API_PORT}|g" "$KUBECONFIG_PATH"

    echo ""
    echo "=== Cluster ready ==="
    echo "  export KUBECONFIG=${KUBECONFIG_PATH}"
    echo "  ssh -i ${SSH_KEY} -p ${SSH_PORT} root@localhost"
    echo "  PID: $(cat "$QEMU_PID")"
}

cmd_down() {
    if [[ -f "$QEMU_PID" ]]; then
        local pid
        pid=$(cat "$QEMU_PID")
        if kill -0 "$pid" 2>/dev/null; then
            echo "Stopping cluster (PID ${pid})..."
            kill "$pid"
            local i
            for i in $(seq 1 10); do
                kill -0 "$pid" 2>/dev/null || break
                sleep 1
            done
            kill -9 "$pid" 2>/dev/null || true
        fi
        rm -f "$QEMU_PID"
    fi
    rm -f "$OVERLAY_IMAGE"
    echo "Cluster stopped."
}

cmd_ssh() {
    ssh_cmd "$@"
}

cmd_kubeconfig() {
    if [[ -f "$KUBECONFIG_PATH" ]]; then
        echo "$KUBECONFIG_PATH"
    else
        echo "No kubeconfig. Is the cluster running?" >&2
        return 1
    fi
}

cmd_deploy() {
    if ! check_running; then
        echo "Cluster not running. Run 'up' first."
        return 1
    fi

    export KUBECONFIG="$KUBECONFIG_PATH"

    echo "=== Deploying DeviceNetwork ==="

    echo "  Building container image..."
    docker build -q -t devicenetwork:e2e -f "$PROJECT_DIR/build/Dockerfile" "$PROJECT_DIR"

    echo "  Loading image into k3s..."
    docker save devicenetwork:e2e | ssh_cmd "k3s ctr images import -"

    echo "  Applying manifests..."
    ssh_cmd "k3s kubectl apply -f -" < "$PROJECT_DIR/deployment/devicenetwork.io_devicenetworks.yaml"
    ssh_cmd "k3s kubectl apply -f -" < "$PROJECT_DIR/deployment/deviceclass.yaml"

    # Patch the DaemonSet to use the local e2e image
    sed \
        -e 's|image:.*|image: docker.io/library/devicenetwork:e2e|' \
        -e 's|imagePullPolicy:.*|imagePullPolicy: Never|' \
        "$PROJECT_DIR/deployment/device-network.yaml" \
        | ssh_cmd "k3s kubectl apply -f -"

    echo "  Waiting for DaemonSet rollout..."
    ssh_cmd "k3s kubectl rollout status daemonset/devicenetwork --timeout=120s" || true

    echo "=== DeviceNetwork deployed ==="
}

cmd_clean() {
    cmd_down 2>/dev/null || true
    echo "Cleaning ${E2E_DIR}..."
    rm -rf "$E2E_DIR"
    echo "Done."
}

cmd_help() {
    cat <<EOF
Usage: $0 <command>

Commands:
  build       Build base VM image with Alpine + k3s (one-time, ~60-90s)
  up          Start cluster with igb SR-IOV NICs (~5s with direct kernel boot)
  down        Stop cluster and remove overlay
  ssh [cmd]   SSH into the VM (optionally run a command)
  kubeconfig  Print kubeconfig file path
  deploy      Build + deploy DeviceNetwork into the cluster
  clean       Stop cluster and remove all generated artifacts

Environment variables:
  E2E_DIR          Output directory         (default: _output/e2e)
  ALPINE_VERSION   Alpine major.minor       (default: ${ALPINE_VERSION})
  ALPINE_RELEASE   Alpine full version      (default: ${ALPINE_RELEASE})
  K3S_VERSION      k3s release              (default: ${K3S_VERSION})
  VM_MEMORY        VM memory in MB          (default: ${VM_MEMORY})
  VM_CPUS          VM CPU count             (default: ${VM_CPUS})
  SSH_PORT         Host SSH forward port    (default: ${SSH_PORT})
  API_PORT         Host k8s API port        (default: ${API_PORT})
  IGB_COUNT        Number of igb PF NICs    (default: ${IGB_COUNT})
  SRIOV_VF_COUNT   VFs to create per PF     (default: ${SRIOV_VF_COUNT})
EOF
}

case "${1:-help}" in
    build)      cmd_build ;;
    up)         cmd_up ;;
    down)       cmd_down ;;
    ssh)        shift; cmd_ssh "$@" ;;
    kubeconfig) cmd_kubeconfig ;;
    deploy)     cmd_deploy ;;
    clean)      cmd_clean ;;
    *)          cmd_help ;;
esac
