#!/usr/bin/env bash
# This file was generated by AI.
#
# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Manage a QEMU-based e2e test cluster with SR-IOV (igb) emulation.
#
# Prerequisites: qemu-system-x86_64, qemu-img, genisoimage (or mkisofs/xorriso),
#                curl, ssh, KVM support (/dev/kvm).
#
# Usage:
#   hack/e2e/e2e-qemu-cluster.sh up          Start cluster (~2-3 min)
#   hack/e2e/e2e-qemu-cluster.sh down        Stop cluster
#   hack/e2e/e2e-qemu-cluster.sh ssh [cmd]   SSH into the VM
#   hack/e2e/e2e-qemu-cluster.sh kubeconfig  Print kubeconfig path
#   hack/e2e/e2e-qemu-cluster.sh deploy      Build and deploy DeviceNetwork into the cluster

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

E2E_DIR="${E2E_DIR:-${PROJECT_DIR}/_output/e2e}"
ALPINE_VERSION="${ALPINE_VERSION:-3.21}"
ALPINE_RELEASE="${ALPINE_RELEASE:-3.21.6}"
K3S_VERSION="${K3S_VERSION:-v1.36.3+k3s1}"
VM_MEMORY="${VM_MEMORY:-4096}"
VM_CPUS="${VM_CPUS:-4}"
SSH_PORT="${SSH_PORT:-2222}"
API_PORT="${API_PORT:-6443}"
E2E_IMAGE="${E2E_IMAGE:-devicenetwork:e2e}"
IGB_COUNT="${IGB_COUNT:-2}"
IGB_PLAIN_COUNT="${IGB_PLAIN_COUNT:-2}"
VIRTIO_NET_COUNT="${VIRTIO_NET_COUNT:-2}"
SRIOV_VF_COUNT="${SRIOV_VF_COUNT:-4}"

VM_IMAGE="${E2E_DIR}/vm.qcow2"
SEED_ISO="${E2E_DIR}/seed.iso"
SSH_KEY="${E2E_DIR}/id_ed25519"
QEMU_PID="${E2E_DIR}/qemu.pid"
KUBECONFIG_PATH="${E2E_DIR}/kubeconfig"
SERIAL_LOG="${E2E_DIR}/serial.log"
CLOUD_IMAGE="${E2E_DIR}/alpine-cloud.qcow2"

CLOUD_IMAGE_URL="https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/releases/cloud/nocloud_alpine-${ALPINE_RELEASE}-x86_64-bios-cloudinit-r0.qcow2"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

ssh_cmd() {
    ssh -q \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o ConnectTimeout=5 \
        -i "$SSH_KEY" \
        -p "$SSH_PORT" \
        root@localhost "$@"
}

scp_from() {
    scp -q \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -i "$SSH_KEY" \
        -P "$SSH_PORT" \
        "root@localhost:$1" "$2"
}

wait_ssh() {
    local timeout="${1:-120}"
    local start=$SECONDS
    echo "  Waiting for SSH..."
    while ! ssh_cmd true 2>/dev/null; do
        if (( SECONDS - start > timeout )); then
            echo "ERROR: SSH not reachable after ${timeout}s"
            return 1
        fi
        sleep 1
    done
}

wait_k3s() {
    local timeout="${1:-120}"
    echo "  Waiting for k3s..."
    local start=$SECONDS
    while ! ssh_cmd "k3s kubectl get nodes 2>/dev/null | grep -q ' Ready'" 2>/dev/null; do
        if (( SECONDS - start > timeout )); then
            echo "ERROR: k3s not ready after ${timeout}s"
            return 1
        fi
        sleep 2
    done
}

check_running() {
    [[ -f "$QEMU_PID" ]] && kill -0 "$(cat "$QEMU_PID")" 2>/dev/null
}

make_seed_iso() {
    local tmpdir
    tmpdir=$(mktemp -d)
    trap "rm -rf $tmpdir" RETURN

    local ssh_pubkey
    ssh_pubkey=$(cat "${SSH_KEY}.pub")

    cat > "$tmpdir/meta-data" <<EOF
instance-id: e2e-node
local-hostname: e2e-node
EOF

    cat > "$tmpdir/user-data" <<USERDATA
#cloud-config
disable_root: false
ssh_pwauth: false

write_files:
  - path: /usr/lib/udev/net-name-pci.sh
    permissions: '0755'
    content: |
      #!/bin/sh
      dev="/sys/class/net/\$1/device"
      [ -L "\$dev" ] || exit 1
      if [ -L "\$dev/physfn" ]; then
        pci=\$(basename \$(readlink -f "\$dev/physfn"))
        vfidx=""
        for vf in "\$dev/physfn"/virtfn*; do
          [ -L "\$vf" ] || continue
          if [ "\$(basename \$(readlink -f "\$vf"))" = "\$(basename \$(readlink -f "\$dev"))" ]; then
            vfidx=\$(echo "\$vf" | sed 's/.*virtfn//')
            break
          fi
        done
        func=\$(( vfidx + 1 ))
      else
        pci=\$(basename \$(readlink -f "\$dev"))
        func=\$(echo "\$pci" | cut -d. -f2)
      fi
      bus=\$(printf %d 0x\$(echo "\$pci" | cut -d: -f2))
      rest=\$(echo "\$pci" | cut -d: -f3)
      slot=\$(printf %d 0x\$(echo "\$rest" | cut -d. -f1))
      if [ "\$func" = "0" ]; then echo "enp\${bus}s\${slot}"; else echo "enp\${bus}s\${slot}f\${func}"; fi
  - path: /usr/lib/udev/rules.d/80-net-name-slot.rules
    content: |
      SUBSYSTEM=="net", ACTION=="add", ATTR{type}=="1", DRIVERS=="igb", PROGRAM="/usr/lib/udev/net-name-pci.sh %k", NAME="%c"
      SUBSYSTEM=="net", ACTION=="add", ATTR{type}=="1", DRIVERS=="igbvf", PROGRAM="/usr/lib/udev/net-name-pci.sh %k", NAME="%c"

users:
  - name: root
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_pubkey}

runcmd:
  - sed -i 's|^#\(.*community\)|\1|' /etc/apk/repositories
  - apk update
  - apk add linux-lts
  - mkinitfs \$(ls /lib/modules/ | grep lts | head -1)
  - apk add --no-cache bash curl pciutils iproute2 iptables cni-plugins numactl-tools ethtool eudev
  - setup-devd udev
  - rm -f /etc/udev/rules.d/70-persistent-net.rules
  - rc-update add cgroups default
  - rc-service cgroups start || true
  - printf 'igb\nigbvf\nbr_netfilter\n' >> /etc/modules
  - mount --make-rshared /
  - printf '#!/sbin/openrc-run\ncommand="/bin/mount"\ncommand_args="--make-rshared /"\n' > /etc/init.d/shared-mount
  - chmod +x /etc/init.d/shared-mount
  - rc-update add shared-mount boot
  - sed -i 's/vmlinuz-virt/vmlinuz-lts/g; s/initramfs-virt/initramfs-lts/g' /boot/extlinux.conf
  - |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="${K3S_VERSION}" INSTALL_K3S_EXEC="server --disable=traefik --disable=metrics-server --disable=servicelb --node-name=e2e-node --write-kubeconfig-mode=644" sh -
  - touch /var/lib/cloud-init-done
USERDATA

    if command -v genisoimage &>/dev/null; then
        genisoimage -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
            "$tmpdir/user-data" "$tmpdir/meta-data"
    elif command -v mkisofs &>/dev/null; then
        mkisofs -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
            "$tmpdir/user-data" "$tmpdir/meta-data"
    elif command -v xorriso &>/dev/null; then
        xorriso -as mkisofs -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
            "$tmpdir/user-data" "$tmpdir/meta-data"
    else
        echo "ERROR: Need genisoimage, mkisofs, or xorriso to create the seed ISO."
        return 1
    fi
}

launch_qemu() {
    local image="$1"
    shift
    local extra_args=("$@")

    local mem_per_node=$(( VM_MEMORY / 2 ))
    local cpus_per_node=$(( VM_CPUS / 2 ))
    local total_nics=$(( IGB_COUNT + IGB_PLAIN_COUNT + VIRTIO_NET_COUNT ))
    local first_half=$(( total_nics / 2 ))

    local qemu_args=(
        qemu-system-x86_64
        -machine q35,accel=kvm
        -cpu host
        -m "$VM_MEMORY"
        -smp "${VM_CPUS},sockets=2,cores=${cpus_per_node},threads=1"
        -object "memory-backend-ram,id=mem0,size=${mem_per_node}M"
        -object "memory-backend-ram,id=mem1,size=${mem_per_node}M"
        -numa "node,nodeid=0,cpus=0-$(( cpus_per_node - 1 )),memdev=mem0"
        -numa "node,nodeid=1,cpus=${cpus_per_node}-$(( VM_CPUS - 1 )),memdev=mem1"
        -device "pxb-pcie,id=pci_numa0,bus_nr=16,bus=pcie.0,numa_node=0"
        -device "pxb-pcie,id=pci_numa1,bus_nr=32,bus=pcie.0,numa_node=1"
        -display none
        -serial "file:${SERIAL_LOG}"
        -drive "file=${image},if=none,id=disk0,format=qcow2"
        -device "virtio-blk-pci,drive=disk0,bus=pcie.0"
        -netdev "user,id=mgmt,hostfwd=tcp::${SSH_PORT}-:22,hostfwd=tcp::${API_PORT}-:6443"
        -device virtio-net-pci,netdev=mgmt,bus=pcie.0
    )

    local nic_idx=0
    for i in $(seq 1 "$IGB_COUNT"); do
        nic_idx=$(( nic_idx + 1 ))
        local pci_bus=$(( nic_idx > first_half ? 1 : 0 ))
        qemu_args+=(
            -device "pcie-root-port,id=rp${nic_idx},bus=pci_numa${pci_bus},chassis=${nic_idx}"
            -device "igb,bus=rp${nic_idx},id=igb${nic_idx}"
        )
    done

    for i in $(seq 1 "$IGB_PLAIN_COUNT"); do
        nic_idx=$(( nic_idx + 1 ))
        local pci_bus=$(( nic_idx > first_half ? 1 : 0 ))
        qemu_args+=(
            -device "pcie-root-port,id=rp${nic_idx},bus=pci_numa${pci_bus},chassis=${nic_idx}"
            -device "igb,bus=rp${nic_idx},id=igb${nic_idx}"
        )
    done

    for i in $(seq 1 "$VIRTIO_NET_COUNT"); do
        nic_idx=$(( nic_idx + 1 ))
        local pci_bus=$(( nic_idx > first_half ? 1 : 0 ))
        qemu_args+=(
            -device "pcie-root-port,id=rp${nic_idx},bus=pci_numa${pci_bus},chassis=${nic_idx}"
            -device "virtio-net-pci,bus=rp${nic_idx},id=virtio${i}"
        )
    done

    qemu_args+=("${extra_args[@]}")

    "${qemu_args[@]}" &
    echo $! > "$QEMU_PID"
}

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------

cmd_up() {
    if check_running; then
        echo "Cluster already running (PID $(cat "$QEMU_PID"))."
        return 0
    fi

    echo "=== Starting e2e cluster ==="
    mkdir -p "$E2E_DIR"

    if [[ ! -f "$SSH_KEY" ]]; then
        ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -q
        echo "  Generated SSH key."
    fi

    if [[ ! -f "$CLOUD_IMAGE" ]]; then
        echo "  Downloading Alpine ${ALPINE_RELEASE} cloud image..."
        curl -fSL --progress-bar -o "$CLOUD_IMAGE" "$CLOUD_IMAGE_URL"
    fi

    echo "  Creating VM disk..."
    cp "$CLOUD_IMAGE" "$VM_IMAGE"
    qemu-img resize -q "$VM_IMAGE" 10G

    make_seed_iso

    echo "  Booting VM (provisioning takes ~2-3 min on first run)..."
    launch_qemu "$VM_IMAGE" \
        -drive "file=${SEED_ISO},if=none,id=seed,media=cdrom" \
        -device "virtio-blk-pci,drive=seed,bus=pcie.0"

    wait_ssh 180

    echo "  Waiting for cloud-init..."
    local start=$SECONDS
    while ! ssh_cmd "test -f /var/lib/cloud-init-done" 2>/dev/null; do
        if (( SECONDS - start > 300 )); then
            echo "ERROR: cloud-init timed out"
            cmd_down
            return 1
        fi
        sleep 5
    done

    echo "  Rebooting into LTS kernel..."
    ssh_cmd "reboot" || true
    sleep 5
    wait_ssh 60

    wait_k3s 120

    echo "  Creating SR-IOV VFs on first ${IGB_COUNT} igb PFs..."
    ssh_cmd "modprobe igb; modprobe igbvf" || true
    local pf_addrs
    pf_addrs=$(ssh_cmd "ls -d /sys/bus/pci/drivers/igb/0000:* 2>/dev/null | xargs -I{} basename {} | head -n ${IGB_COUNT}" || true)
    for addr in $pf_addrs; do
        ssh_cmd "echo ${SRIOV_VF_COUNT} > /sys/bus/pci/devices/${addr}/sriov_numvfs" 2>/dev/null || true
        local pf_iface
        pf_iface=$(ssh_cmd "ls /sys/bus/pci/devices/${addr}/net/ 2>/dev/null | head -1" || true)
        echo "  PF ${addr} (${pf_iface:-unknown}): ${SRIOV_VF_COUNT} VFs"
    done

    scp_from "/etc/rancher/k3s/k3s.yaml" "$KUBECONFIG_PATH"
    sed -i "s|127.0.0.1:6443|127.0.0.1:${API_PORT}|g" "$KUBECONFIG_PATH"

    echo ""
    echo "=== Cluster ready ==="
    echo "  export KUBECONFIG=${KUBECONFIG_PATH}"
    echo "  ssh -i ${SSH_KEY} -p ${SSH_PORT} root@localhost"
    echo "  PID: $(cat "$QEMU_PID")"
}

cmd_down() {
    if [[ -f "$QEMU_PID" ]]; then
        local pid
        pid=$(cat "$QEMU_PID")
        if kill -0 "$pid" 2>/dev/null; then
            echo "Stopping cluster (PID ${pid})..."
            kill "$pid"
            local i
            for i in $(seq 1 10); do
                kill -0 "$pid" 2>/dev/null || break
                sleep 1
            done
            kill -9 "$pid" 2>/dev/null || true
        fi
        rm -f "$QEMU_PID"
    fi
    rm -f "$VM_IMAGE" "$SEED_ISO"
    echo "Cluster stopped."
}

cmd_ssh() {
    ssh_cmd "$@"
}

cmd_kubeconfig() {
    if [[ -f "$KUBECONFIG_PATH" ]]; then
        echo "$KUBECONFIG_PATH"
    else
        echo "No kubeconfig. Is the cluster running?" >&2
        return 1
    fi
}

cmd_deploy() {
    if ! check_running; then
        echo "Cluster not running. Run 'up' first."
        return 1
    fi

    export KUBECONFIG="$KUBECONFIG_PATH"

    echo "=== Deploying DeviceNetwork ==="

    echo "  Loading image ${E2E_IMAGE} into k3s..."
    docker save "$E2E_IMAGE" | ssh_cmd "k3s ctr images import -"

    echo "  Applying manifests..."
    ssh_cmd "k3s kubectl apply -f -" < "$PROJECT_DIR/deployment/devicenetwork.io_devicenetworks.yaml"
    ssh_cmd "k3s kubectl apply -f -" < "$PROJECT_DIR/deployment/deviceclass.yaml"

    sed \
        -e "s|image:.*|image: docker.io/library/${E2E_IMAGE}|" \
        -e 's|imagePullPolicy:.*|imagePullPolicy: Never|' \
        "$PROJECT_DIR/deployment/device-network.yaml" \
        | ssh_cmd "k3s kubectl apply -f -"

    echo "  Waiting for DaemonSet rollout..."
    ssh_cmd "k3s kubectl rollout status daemonset/devicenetwork --timeout=120s" || true

    echo "=== DeviceNetwork deployed ==="
}

cmd_clean() {
    cmd_down 2>/dev/null || true
    echo "Cleaning ${E2E_DIR}..."
    rm -rf "$E2E_DIR"
    echo "Done."
}

cmd_help() {
    cat <<EOF
Usage: $0 <command>

Commands:
  up          Start cluster with Alpine + k3s + igb SR-IOV NICs (~2-3 min)
  down        Stop cluster and remove VM disk
  ssh [cmd]   SSH into the VM (optionally run a command)
  kubeconfig  Print kubeconfig file path
  deploy      Deploy DeviceNetwork into the cluster (build image first)
  clean       Stop cluster and remove all generated artifacts

Environment variables:
  E2E_DIR          Output directory         (default: _output/e2e)
  ALPINE_VERSION   Alpine major.minor       (default: ${ALPINE_VERSION})
  ALPINE_RELEASE   Alpine full version      (default: ${ALPINE_RELEASE})
  K3S_VERSION      k3s release              (default: ${K3S_VERSION})
  VM_MEMORY        VM memory in MB          (default: ${VM_MEMORY})
  VM_CPUS          VM CPU count             (default: ${VM_CPUS})
  SSH_PORT         Host SSH forward port    (default: ${SSH_PORT})
  API_PORT         Host k8s API port        (default: ${API_PORT})
  IGB_COUNT        Number of igb SR-IOV PFs  (default: ${IGB_COUNT})
  IGB_PLAIN_COUNT  Number of igb NICs w/o VFs (default: ${IGB_PLAIN_COUNT})
  VIRTIO_NET_COUNT Number of virtio-net NICs (default: ${VIRTIO_NET_COUNT})
  E2E_IMAGE        Container image to deploy (default: ${E2E_IMAGE})
  SRIOV_VF_COUNT   VFs to create per PF     (default: ${SRIOV_VF_COUNT})
EOF
}

case "${1:-help}" in
    up)         cmd_up ;;
    down)       cmd_down ;;
    ssh)        shift; cmd_ssh "$@" ;;
    kubeconfig) cmd_kubeconfig ;;
    deploy)     cmd_deploy ;;
    clean)      cmd_clean ;;
    *)          cmd_help ;;
esac
